#+TITLE: Emacs Shapeless Blog

This is the Emacs package for [[https://github.com/drshapeless/shapeless-blog][shapeless-blog]].

* Prerequisites
- emacs
- rsync
- sqlite3

* Installation
Assume that you have setup a shapeless-blog server and have a domain.

Put ~shapeless-blog.el~ into your load path.
#+begin_src emacs-lisp
  (require 'shapeless-blog)
#+end_src

* Configuration
Put in your remote database location for shapeless-blog.
#+begin_src emacs-lisp
  (setq shapeless-blog-remote-path "dummy@drshapeless.com:shapeless-blog")
#+end_src
* Usage
Open a blank org file, this is the sample template, you may add this
to yasnippets. If anyone of this is missing, the behaviour is unknown.
#+begin_src org
  ,#+title:
  ,#+filetags: :emacs:
  ,#+date:
  ,#+update:
  ,#+id:

#+end_src

Insert the title, and optionally fill in the categories.

If you want multiple tags, use colon to separate them.
#+begin_src org
  ,#+filetags: :emacs:github:
#+end_src

After writing your blog post, =M-x= ~shapeless-blog-create-or-update-post~.

~shapeless-blog.el~ will automatically fill in the DATE, UPDATE, ID.

If you want to update an old post which already has an ID, you should
still use ~shapeless-blog-create-or-update-post~, the UPDATE will
change to present time. The package will automatically choose the
correct method to call.

For advance use, there is another method
~shapeless-blog-create-old-post~. This method can only be use in
creating old blog post. The difference between
~shapeless-blog-create-or-update-post~ and
~shapeless-blog-create-old-post~ is that
latter requires a pre-entered id, while the former automatically
generate a new id and fill it for you.

Also, there is another method ~shapeless-blog-modify-old-post~, this
method will not change the update time to now, and preserve the
original update time.
